services:

  lleego_nginx:
      image: nginx:1.25.5-alpine-slim
      container_name: lleego_nginx
      restart: always
      volumes:
        - ./:/usr/src/app
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - ${DOCKER_NGINX_PORTS}
      depends_on:
        - lleego_php

  lleego_php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      image: lleego_php:1.2.0
      environment:
        PHP_IDE_CONFIG: serverName=lleego_php
      container_name: lleego_php
      restart: always
      user: 1000:1000
      volumes:
        - ./:/usr/src/app
        - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      ports:
        -  ${DOCKER_PHP_PORTS}
      dns:
        - 8.8.8.8

networks:
  lleego-network:
    external: true
